name: Go

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x']
    
    steps:
    - uses: actions/checkout@v4

    - name: OSSF Scorecard action
      uses: ossf/scorecard-action@v2.4.0
      with:
        results_file: ossf_results.sarif
        results_format: sarif
        publish_results: true

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go get .

    - name: Go vet checks
      run: go vet ./...

    - name: Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: go test -v ./...

    - name: Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./Dockerfile
    
    - name: Build Docker image
      run: |
        docker build -t my-app:ci .

